export const projects = [
  {
    id: "solar-farms",
    title: "Solar Farm Initiative",
    shortDescription: "Large-scale solar installations across Zambia",
    fullDescription:
      "Our solar farm initiative is revolutionizing how Zambia generates clean energy. We're deploying utility-scale solar farms in strategic locations across the country, focusing on areas with high solar potential and minimal environmental impact.",
    details: [
      "10+ solar farms operational and under construction",
      "Total capacity: 250MW across all sites",
      "Covering 5,000+ hectares of productive land",
      "Expected to power 500,000+ households",
      "Partnership with international solar technology providers",
      "Local job creation with 2,000+ employment opportunities",
    ],
    impact: "Providing reliable renewable energy to rural and urban communities",
    location: "Northern and Southern Provinces",
    capacity: "250MW",
    status: "Active & Expanding",
  },
  {
    id: "hydroelectric",
    title: "Hydroelectric Power Projects",
    shortDescription: "Harnessing Zambia's water resources",
    fullDescription:
      "Zambia's rivers are a tremendous natural resource. Our hydroelectric projects utilize this power responsibly, upgrading existing facilities and developing new dams to increase capacity while protecting ecosystems.",
    details: [
      "5 major hydroelectric facilities upgraded",
      "2 new dams under construction",
      "Total expanded capacity: 150MW",
      "Sustainable water management practices",
      "Fish and wildlife protection programs",
      "Community benefit-sharing agreements",
    ],
    impact: "Stable, renewable baseload power with minimal emissions",
    location: "Eastern and Western Zambia",
    capacity: "150MW",
    status: "Ongoing Development",
  },
  {
    id: "wind-energy",
    title: "Wind Energy Development",
    shortDescription: "Capturing Zambia's wind potential",
    fullDescription:
      "With favorable wind conditions in certain regions, we're developing wind farms as part of our diversified energy portfolio. Wind turbines complement our solar and hydro operations for year-round energy generation.",
    details: [
      "3 wind farms operational",
      "Advanced weather tracking systems installed",
      "Capacity: 100MW total",
      "1,500+ jobs during construction and operations",
      "Community engagement programs",
      "Technology transfer to local engineers",
    ],
    impact: "Diversified renewable energy sources for energy security",
    location: "Southern Region High Plains",
    capacity: "100MW",
    status: "Growing Portfolio",
  },
  {
    id: "smart-grid",
    title: "Smart Grid Infrastructure",
    shortDescription: "Modernizing Zambia's electrical distribution network",
    fullDescription:
      "A modern power system requires intelligent distribution. Our smart grid technology enables efficient power delivery, reduces losses, and provides real-time monitoring of the entire network.",
    details: [
      "50,000+ smart meters deployed",
      "Real-time monitoring across all provinces",
      "30% reduction in transmission losses",
      "Automated outage detection and response",
      "Customer app for usage tracking",
      "Integration with renewable energy sources",
    ],
    impact: "Efficient power delivery and reduced operational costs",
    location: "Nationwide",
    capacity: "Network-wide",
    status: "Phase 1 Complete",
  },
  {
    id: "community-solar",
    title: "Community Solar Program",
    shortDescription: "Bringing solar to rural communities",
    fullDescription:
      "Empowering communities through distributed solar energy. Our community solar program installs solar panels on public buildings, schools, and health clinics, improving local quality of life.",
    details: [
      "500+ community installations",
      "Schools and clinics powered with solar",
      "Capacity: 50MW distributed",
      "Training programs for local technicians",
      "Maintenance jobs created locally",
      "Improved healthcare and education delivery",
    ],
    impact: "Universal energy access in underserved communities",
    location: "All Provinces",
    capacity: "50MW",
    status: "Expanding Rapidly",
  },
  {
    id: "energy-storage",
    title: "Battery Storage Systems",
    shortDescription: "Solving renewable energy intermittency",
    fullDescription:
      "Energy storage is crucial for reliable renewable power. We're deploying large-scale battery systems across Zambia to store excess solar and wind energy for use during peak demand or low generation periods.",
    details: [
      "5 battery storage facilities operational",
      "500MWh total storage capacity",
      "Support for 24/7 renewable energy supply",
      "Advanced battery management systems",
      "Grid stabilization capabilities",
      "Cost reduction through technology innovation",
    ],
    impact: "Enabling reliable renewable energy around the clock",
    location: "Strategic grid locations",
    capacity: "500MWh",
    status: "Initial Deployment",
  },
]
